fix(cicd): provide CI bundle environment variables

diff --git a/.github/workflows/databricks-ci.yml b/.github/workflows/databricks-ci.yml
--- a/.github/workflows/databricks-ci.yml
+++ b/.github/workflows/databricks-ci.yml
@@ -31,9 +31,13 @@ jobs:
 
     env:
       DATABRICKS_AUTH_TYPE: github-oidc
+
       DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
       DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID }}
       DATABRICKS_TOKEN_AUDIENCE: ${{ vars.DATABRICKS_ACCOUNT_ID }}
+
+      BUNDLE_VAR_msk_bootstrap_servers: ${{ secrets.MSK_BOOTSTRAP_SERVERS }}
+      BUNDLE_VAR_s3_landing_url: ${{ secrets.S3_LANDING_URL }}
 
     steps:
       - name: Checkout repository
@@ -54,6 +58,16 @@ jobs:
 
           test -n "${DATABRICKS_TOKEN_AUDIENCE}" || {
             echo "GitHub environment variable DATABRICKS_ACCOUNT_ID is required."
+            exit 1
+          }
+
+          test -n "${BUNDLE_VAR_msk_bootstrap_servers}" || {
+            echo "GitHub environment secret MSK_BOOTSTRAP_SERVERS is required."
+            exit 1
+          }
+
+          test -n "${BUNDLE_VAR_s3_landing_url}" || {
+            echo "GitHub environment secret S3_LANDING_URL is required."
             exit 1
           }
 
